// Script to define all timeline flavor messages
// These will be generated using MiniMax TTS

export interface FlavorMessage {
    id: string;
    time: number;
    text: string;
    world: 'dark_forest' | 'catacombs' | 'frozen_waste';
}

// Dark Forest messages - every 30 seconds for 15 minutes
export const darkForestMessages: FlavorMessage[] = [
    { id: 'df-001', time: 0, text: "Ah, they come for your borscht, comrade!", world: 'dark_forest' },
    { id: 'df-002', time: 30, text: "They scream louder than accordion at village party!", world: 'dark_forest' },
    { id: 'df-003', time: 60, text: "Domovoi swarm! House spirits very angry about dirty boots!", world: 'dark_forest' },
    { id: 'df-004', time: 90, text: "Mushrooms! But not the good kind babushka puts in soup!", world: 'dark_forest' },
    { id: 'df-005', time: 120, text: "Golems! Heavy like mother-in-law's cooking!", world: 'dark_forest' },
    { id: 'df-006', time: 150, text: "Werewolf! Even hairier than uncle Dmitri!", world: 'dark_forest' },
    { id: 'df-007', time: 180, text: "More enemies than potatoes in harvest season!", world: 'dark_forest' },
    { id: 'df-008', time: 210, text: "Ghost wolves! They howl for your pierogis!", world: 'dark_forest' },
    { id: 'df-009', time: 240, text: "Leshy Shamans! Forest magic goes brrrrr!", world: 'dark_forest' },
    { id: 'df-010', time: 270, text: "BIG BOSS IS COMING! Hide behind the turnips!", world: 'dark_forest' },
    { id: 'df-011', time: 300, text: "Two werewolves! Double the fleas!", world: 'dark_forest' },
    { id: 'df-012', time: 330, text: "More golems! They have stones for brains!", world: 'dark_forest' },
    { id: 'df-013', time: 360, text: "Ghost pack! They want belly rubs from beyond!", world: 'dark_forest' },
    { id: 'df-014', time: 390, text: "Mushroom army! Nature's revenge for all that foraging!", world: 'dark_forest' },
    { id: 'df-015', time: 420, text: "Ancient Treant! This tree has been angry for 1000 years!", world: 'dark_forest' },
    { id: 'df-016', time: 450, text: "Baby trees! They grow up so fast, then attack you!", world: 'dark_forest' },
    { id: 'df-017', time: 480, text: "Wolf spirits! They still want treats from beyond grave!", world: 'dark_forest' },
    { id: 'df-018', time: 510, text: "Werewolf pack! Like very angry book club!", world: 'dark_forest' },
    { id: 'df-019', time: 540, text: "Wasps! Run faster than babushka chasing grandchildren!", world: 'dark_forest' },
    { id: 'df-020', time: 570, text: "Domovoi everywhere! House is very unclean!", world: 'dark_forest' },
    { id: 'df-021', time: 600, text: "Shaman convention! Very magical, very dangerous!", world: 'dark_forest' },
    { id: 'df-022', time: 630, text: "40 screechers! Like 40 mother-in-laws at once!", world: 'dark_forest' },
    { id: 'df-023', time: 660, text: "Shadow stalkers! They follow you like tax collector!", world: 'dark_forest' },
    { id: 'df-024', time: 690, text: "100 Domovoi! Did entire village forget to clean?!", world: 'dark_forest' },
    { id: 'df-025', time: 720, text: "Two Treants! Forest having family reunion!", world: 'dark_forest' },
    { id: 'df-026', time: 750, text: "Elite Golems! They skip leg day never!", world: 'dark_forest' },
    { id: 'df-027', time: 780, text: "Shaman army! Forest magic at maximum blyat!", world: 'dark_forest' },
    { id: 'df-028', time: 810, text: "40 ghost wolves! They still want walkies!", world: 'dark_forest' },
    { id: 'df-029', time: 840, text: "Werewolf army! Full moon special discount!", world: 'dark_forest' },
    { id: 'df-030', time: 870, text: "CHERNOBOG! Dark lord himself! Even bears run from this one!", world: 'dark_forest' },
    { id: 'df-031', time: 900, text: "VICTORY! You are champion! Even the bears applaud!", world: 'dark_forest' },
];

// Catacombs messages - every 30 seconds for 20+ minutes
export const catacombsMessages: FlavorMessage[] = [
    { id: 'cat-001', time: 0, text: "You descend into the ancient catacombs...", world: 'catacombs' },
    { id: 'cat-002', time: 30, text: "Bones rattle in the darkness! Very spooky down here!", world: 'catacombs' },
    { id: 'cat-003', time: 60, text: "Tiny creatures swarm from cracks in the walls!", world: 'catacombs' },
    { id: 'cat-004', time: 90, text: "The smell! Like uncle's socks after harvest festival!", world: 'catacombs' },
    { id: 'cat-005', time: 120, text: "Burning spirits emerge from the walls! Hot hot hot!", world: 'catacombs' },
    { id: 'cat-006', time: 150, text: "More skeletons! They need calcium, comrade!", world: 'catacombs' },
    { id: 'cat-007', time: 180, text: "Stone sentinels guard the deeper passages!", world: 'catacombs' },
    { id: 'cat-008', time: 210, text: "A massive Bone Horror claws its way up!", world: 'catacombs' },
    { id: 'cat-009', time: 240, text: "Frost bats! They want your warm blood!", world: 'catacombs' },
    { id: 'cat-010', time: 270, text: "The walls are closing in! Or maybe that's claustrophobia!", world: 'catacombs' },
    { id: 'cat-011', time: 300, text: "The Crypt Lord awakens! He slept for centuries!", world: 'catacombs' },
    { id: 'cat-012', time: 330, text: "Flame wraiths everywhere! Like disco inferno!", world: 'catacombs' },
    { id: 'cat-013', time: 360, text: "Stone golems march! They are not rolling stones!", world: 'catacombs' },
    { id: 'cat-014', time: 390, text: "An Infernal Wraith rises from the depths!", world: 'catacombs' },
    { id: 'cat-015', time: 420, text: "More crawlers! They have too many legs!", world: 'catacombs' },
    { id: 'cat-016', time: 450, text: "The ground shakes! Something big is coming!", world: 'catacombs' },
    { id: 'cat-017', time: 480, text: "Ancient bones reform! They don't stay dead!", world: 'catacombs' },
    { id: 'cat-018', time: 510, text: "Screechers echo! My ears, comrade!", world: 'catacombs' },
    { id: 'cat-019', time: 540, text: "The Crypt Guardian awakens from its eternal vigil!", world: 'catacombs' },
    { id: 'cat-020', time: 570, text: "Fire and ice mix! Like hot borscht with cold vodka!", world: 'catacombs' },
    { id: 'cat-021', time: 600, text: "A Stone Sentinel rises! Very rocky situation!", world: 'catacombs' },
    { id: 'cat-022', time: 630, text: "Bruisers charge! Like bulls in porcelain shop!", world: 'catacombs' },
    { id: 'cat-023', time: 660, text: "The deeper we go, the worse it gets!", world: 'catacombs' },
    { id: 'cat-024', time: 690, text: "Elite bone crawler! Extra crunchy!", world: 'catacombs' },
    { id: 'cat-025', time: 720, text: "Domovoi found their way down here too!", world: 'catacombs' },
    { id: 'cat-026', time: 750, text: "Flame wraiths multiply! Too hot to handle!", world: 'catacombs' },
    { id: 'cat-027', time: 780, text: "Stone golem elite! Twice the rock, twice the pain!", world: 'catacombs' },
    { id: 'cat-028', time: 810, text: "We are getting close to the bottom!", world: 'catacombs' },
    { id: 'cat-029', time: 840, text: "A Titanic Golem blocks the path!", world: 'catacombs' },
    { id: 'cat-030', time: 870, text: "Another Crypt Guardian stirs!", world: 'catacombs' },
    { id: 'cat-031', time: 900, text: "The army of the dead marches!", world: 'catacombs' },
    { id: 'cat-032', time: 930, text: "Elite wraiths! They burn with ancient hatred!", world: 'catacombs' },
    { id: 'cat-033', time: 960, text: "Stone sentinels everywhere! Like garden gnomes of doom!", world: 'catacombs' },
    { id: 'cat-034', time: 990, text: "The catacombs shake! Something approaches!", world: 'catacombs' },
    { id: 'cat-035', time: 1020, text: "Wave after wave! They just keep coming!", world: 'catacombs' },
    { id: 'cat-036', time: 1050, text: "Frost golems join the fight! Now we have two problems!", world: 'catacombs' },
    { id: 'cat-037', time: 1080, text: "Elite stone golem! Built like brick house!", world: 'catacombs' },
    { id: 'cat-038', time: 1110, text: "Another flame wraith elite! Fire sale continues!", world: 'catacombs' },
    { id: 'cat-039', time: 1140, text: "The deepest level approaches!", world: 'catacombs' },
    { id: 'cat-040', time: 1170, text: "The Ancient Crypt Lord rises from the deepest tomb!", world: 'catacombs' },
    { id: 'cat-041', time: 1200, text: "Final battle begins! Fight for motherland!", world: 'catacombs' },
];

// Frozen Waste messages - every 30 seconds for 30 minutes
export const frozenWasteMessages: FlavorMessage[] = [
    { id: 'fw-001', time: 0, text: "Frozen spirits emerge from the blizzard...", world: 'frozen_waste' },
    { id: 'fw-002', time: 30, text: "Ice witches weave their snares! Very cold magic!", world: 'frozen_waste' },
    { id: 'fw-003', time: 60, text: "Frost wolves hunt in the storm! They smell your fear!", world: 'frozen_waste' },
    { id: 'fw-004', time: 90, text: "Frozen giants awaken! Big boys from Siberia!", world: 'frozen_waste' },
    { id: 'fw-005', time: 120, text: "The cold bites deep! Like ex-girlfriend's words!", world: 'frozen_waste' },
    { id: 'fw-006', time: 150, text: "Ice golems march forward! Coolest enemies yet!", world: 'frozen_waste' },
    { id: 'fw-007', time: 180, text: "A Frost Wraith materializes from the ice!", world: 'frozen_waste' },
    { id: 'fw-008', time: 210, text: "Living ice forms from the permafrost!", world: 'frozen_waste' },
    { id: 'fw-009', time: 240, text: "Kikimora spirits! Very annoying house ghosts!", world: 'frozen_waste' },
    { id: 'fw-010', time: 270, text: "The blizzard intensifies! Cannot see hand in front of face!", world: 'frozen_waste' },
    { id: 'fw-011', time: 300, text: "A colossal Ice Golem rises from the permafrost!", world: 'frozen_waste' },
    { id: 'fw-012', time: 330, text: "The Ice Maiden's song fills the air! Cover ears!", world: 'frozen_waste' },
    { id: 'fw-013', time: 360, text: "More zmora! Sleep demons want your dreams!", world: 'frozen_waste' },
    { id: 'fw-014', time: 390, text: "Ice shards fly! Nature's angry snowball fight!", world: 'frozen_waste' },
    { id: 'fw-015', time: 420, text: "Snow wraiths phase through the blizzard!", world: 'frozen_waste' },
    { id: 'fw-016', time: 450, text: "Ancient ice-covered treants stir! Frozen forest walks!", world: 'frozen_waste' },
    { id: 'fw-017', time: 480, text: "Frost bats swarm! They want warm blood!", world: 'frozen_waste' },
    { id: 'fw-018', time: 510, text: "The temperature drops! Colder than mother's heart when you forget her birthday!", world: 'frozen_waste' },
    { id: 'fw-019', time: 540, text: "A Frost Giant awakens from eternal slumber!", world: 'frozen_waste' },
    { id: 'fw-020', time: 570, text: "Ice elementals form! Winter is very much here!", world: 'frozen_waste' },
    { id: 'fw-021', time: 600, text: "Another Ice Golem emerges from the blizzard!", world: 'frozen_waste' },
    { id: 'fw-022', time: 630, text: "Frozen werewolves! Even fleas are frozen!", world: 'frozen_waste' },
    { id: 'fw-023', time: 660, text: "The permafrost cracks! Something ancient stirs!", world: 'frozen_waste' },
    { id: 'fw-024', time: 690, text: "Screechers join the frozen horde!", world: 'frozen_waste' },
    { id: 'fw-025', time: 720, text: "An Ice Golem shatters through the glacier!", world: 'frozen_waste' },
    { id: 'fw-026', time: 750, text: "Stone golems covered in ice! Double trouble!", world: 'frozen_waste' },
    { id: 'fw-027', time: 780, text: "The wind howls like babushka at lazy grandson!", world: 'frozen_waste' },
    { id: 'fw-028', time: 810, text: "Elite ice wraith! Extra frosty!", world: 'frozen_waste' },
    { id: 'fw-029', time: 840, text: "An Ice Wraith descends upon you!", world: 'frozen_waste' },
    { id: 'fw-030', time: 870, text: "Frozen undead march! They do not feel cold!", world: 'frozen_waste' },
    { id: 'fw-031', time: 900, text: "The Ancient Frozen Treant awakens!", world: 'frozen_waste' },
    { id: 'fw-032', time: 930, text: "More frost giants! Like family reunion in Siberia!", world: 'frozen_waste' },
    { id: 'fw-033', time: 960, text: "Ice storms rage! Even vodka is frozen!", world: 'frozen_waste' },
    { id: 'fw-034', time: 990, text: "Kikimora multiply! House spirits have union meeting!", world: 'frozen_waste' },
    { id: 'fw-035', time: 1020, text: "The frozen army grows stronger!", world: 'frozen_waste' },
    { id: 'fw-036', time: 1050, text: "Zmora horde! Nightmares become real!", world: 'frozen_waste' },
    { id: 'fw-037', time: 1080, text: "Another Frost Giant joins the hunt!", world: 'frozen_waste' },
    { id: 'fw-038', time: 1110, text: "Ice golems everywhere! Like frozen statues of doom!", world: 'frozen_waste' },
    { id: 'fw-039', time: 1140, text: "The wasteland shows no mercy!", world: 'frozen_waste' },
    { id: 'fw-040', time: 1170, text: "The Frost Colossus appears! Biggest ice cube ever!", world: 'frozen_waste' },
    { id: 'fw-041', time: 1200, text: "Elite enemies swarm! This is getting serious!", world: 'frozen_waste' },
    { id: 'fw-042', time: 1230, text: "Frozen wraiths multiply! Like snow in winter!", world: 'frozen_waste' },
    { id: 'fw-043', time: 1260, text: "Ancient ice spirits join the battle!", world: 'frozen_waste' },
    { id: 'fw-044', time: 1290, text: "The blizzard reaches maximum fury!", world: 'frozen_waste' },
    { id: 'fw-045', time: 1320, text: "Stone sentinels frozen in ice march forward!", world: 'frozen_waste' },
    { id: 'fw-046', time: 1350, text: "More elite enemies! They mean business!", world: 'frozen_waste' },
    { id: 'fw-047', time: 1380, text: "Frost giants form battle line!", world: 'frozen_waste' },
    { id: 'fw-048', time: 1410, text: "The ice cracks beneath your feet!", world: 'frozen_waste' },
    { id: 'fw-049', time: 1440, text: "Werewolves join the frozen pack!", world: 'frozen_waste' },
    { id: 'fw-050', time: 1470, text: "Another Frost Colossus emerges!", world: 'frozen_waste' },
    { id: 'fw-051', time: 1500, text: "The frozen wastes throw everything at you!", world: 'frozen_waste' },
    { id: 'fw-052', time: 1530, text: "Elite ice golems! Ice age begins!", world: 'frozen_waste' },
    { id: 'fw-053', time: 1560, text: "Ancient frozen treants awaken! Forest revenge!", world: 'frozen_waste' },
    { id: 'fw-054', time: 1590, text: "Stone golems join ice army!", world: 'frozen_waste' },
    { id: 'fw-055', time: 1620, text: "Kikimora elite! Head house spirit very angry!", world: 'frozen_waste' },
    { id: 'fw-056', time: 1650, text: "The final wave approaches!", world: 'frozen_waste' },
    { id: 'fw-057', time: 1680, text: "Frozen undead army marches!", world: 'frozen_waste' },
    { id: 'fw-058', time: 1710, text: "Frost Colossus leads the charge!", world: 'frozen_waste' },
    { id: 'fw-059', time: 1740, text: "MOROZKO, the Frost King approaches!", world: 'frozen_waste' },
    { id: 'fw-060', time: 1770, text: "Morozko, the Frost King, has arrived! FINAL BATTLE!", world: 'frozen_waste' },
];

export const allMessages = [
    ...darkForestMessages,
    ...catacombsMessages,
    ...frozenWasteMessages,
];

console.log(`Total messages to generate: ${allMessages.length}`);
console.log(`Dark Forest: ${darkForestMessages.length}`);
console.log(`Catacombs: ${catacombsMessages.length}`);
console.log(`Frozen Waste: ${frozenWasteMessages.length}`);
